function(ouaexp_configure_common_unit_tests)
    ouaexp_add_test(ouaexp_tests                    test_opcua.cpp)
    ouaexp_add_test(ouaexp_tests_settings           test_appsettings.cpp)
    ouaexp_add_test(ouaexp_tests_settings_isolation test_settingsisolation.cpp)
    ouaexp_add_test(ouaexp_tests_profiles           test_profiles.cpp)
    ouaexp_add_test(ouaexp_tests_models_opcua_capabilities test_models_opcua_capabilities.cpp)
    ouaexp_add_test(ouaexp_tests_models_simple test_models_simple.cpp)
    ouaexp_add_test(ouaexp_tests_models_data_access_core test_models_data_access_core.cpp)
    ouaexp_add_test(ouaexp_tests_models_data_access_presentation test_models_data_access_presentation.cpp)
    ouaexp_add_test(ouaexp_tests_models_attributes test_models_attributes.cpp)
    ouaexp_add_test(ouaexp_tests_models_csv_exporter test_models_csv_exporter.cpp)
    ouaexp_add_test(ouaexp_tests_models_events test_models_events.cpp)
    ouaexp_add_test(ouaexp_tests_models_history test_models_history.cpp)
    ouaexp_add_test(ouaexp_tests_models_log test_models_log.cpp)
    ouaexp_add_test(ouaexp_tests_models_node_info test_models_node_info.cpp)
    ouaexp_add_test(ouaexp_tests_models_references test_models_references.cpp)
    ouaexp_add_test(ouaexp_tests_models_subscriptions test_models_subscriptions.cpp)
    ouaexp_add_test(ouaexp_tests_address_space_model test_addressspacemodel.cpp)
    ouaexp_add_test(ouaexp_tests_server_discovery_model test_serverdiscoverymodel.cpp)
    ouaexp_add_test(ouaexp_tests_node_search_crawler test_nodesearchcrawler.cpp)
    ouaexp_add_test(ouaexp_tests_subtree_variable_crawler test_subtreevariablecrawler.cpp)
    ouaexp_add_test(ouaexp_tests_namespace_crawler  test_namespacecrawler.cpp)
    ouaexp_add_test(ouaexp_tests_secrets            test_secretstore.cpp)
    ouaexp_add_test(ouaexp_tests_pkimanager         test_pkimanager.cpp)
    ouaexp_add_test(ouaexp_tests_formatter_names test_attributeformatter_names.cpp)
    ouaexp_add_test(ouaexp_tests_formatter_attributes test_attributeformatter_attributes.cpp)
    ouaexp_add_test(ouaexp_tests_formatter_values test_attributeformatter_values.cpp)
    ouaexp_add_test(ouaexp_tests_formatter_input test_attributeformatter_input.cpp)
    ouaexp_add_test(ouaexp_tests_duration_formatter test_durationformatter.cpp)
    ouaexp_add_test(ouaexp_tests_update_checker     test_updatechecker.cpp)
    ouaexp_add_test(ouaexp_tests_trend_series       test_trendseries.cpp)
    ouaexp_add_test(ouaexp_tests_session            test_session.cpp)
    ouaexp_add_test(ouaexp_tests_controller_connection test_connectioncontroller_connection.cpp)
    ouaexp_add_test(ouaexp_tests_controller_persistence test_connectioncontroller_persistence.cpp)
    ouaexp_add_test(ouaexp_tests_controller_secrets test_connectioncontroller_secrets.cpp)
    ouaexp_add_test(ouaexp_tests_connection_data    test_connectiondata.cpp)
    ouaexp_add_test(ouaexp_tests_qtopcua_internals  test_qtopcuainternals.cpp)
    ouaexp_add_test(ouaexp_tests_utils              test_utils.cpp)
    ouaexp_add_test(ouaexp_tests_license_bundle     test_licensebundle.cpp)
    ouaexp_register_test(ouaexp_tests_modules       test_modules.cpp)
    target_link_libraries(ouaexp_tests_modules PRIVATE ouaexp_modules)
    ouaexp_register_test(ouaexp_tests_chart_zoom    test_chartzoom.cpp)
    target_link_libraries(ouaexp_tests_chart_zoom PRIVATE ouaexp_charting)
endfunction()
