function(ouaexp_configure_common_unit_tests)
    ouaexp_add_test(ouaexp_tests                    test_opcua.cpp)
    ouaexp_add_test(ouaexp_tests_settings           test_appsettings.cpp)
    ouaexp_add_test(ouaexp_tests_profiles           test_profiles.cpp)
    ouaexp_add_test(ouaexp_tests_models             test_models.cpp)
    ouaexp_add_test(ouaexp_tests_secrets            test_secretstore.cpp)
    ouaexp_add_test(ouaexp_tests_formatter          test_attributeformatter.cpp)
    ouaexp_add_test(ouaexp_tests_controller         test_connectioncontroller.cpp)
    ouaexp_add_test(ouaexp_tests_connection_data    test_connectiondata.cpp)
    ouaexp_add_test(ouaexp_tests_qtopcua_internals test_qtopcuainternals.cpp)
endfunction()
