function(ouaexp_configure_common_unit_tests)
    ouaexp_add_test(ouaexp_tests                    test_opcua.cpp)
    ouaexp_add_test(ouaexp_tests_settings           test_appsettings.cpp)
    ouaexp_add_test(ouaexp_tests_profiles           test_profiles.cpp)
    ouaexp_add_test(ouaexp_tests_models             test_models.cpp)
    ouaexp_add_test(ouaexp_tests_address_space_model test_addressspacemodel.cpp)
    ouaexp_add_test(ouaexp_tests_node_search_crawler test_nodesearchcrawler.cpp)
    ouaexp_add_test(ouaexp_tests_namespace_crawler  test_namespacecrawler.cpp)
    ouaexp_add_test(ouaexp_tests_secrets            test_secretstore.cpp)
    ouaexp_add_test(ouaexp_tests_formatter          test_attributeformatter.cpp)
    ouaexp_add_test(ouaexp_tests_duration_formatter test_durationformatter.cpp)
    ouaexp_add_test(ouaexp_tests_update_checker     test_updatechecker.cpp)
    ouaexp_add_test(ouaexp_tests_trend_series       test_trendseries.cpp)
    ouaexp_add_test(ouaexp_tests_session            test_session.cpp)
    ouaexp_add_test(ouaexp_tests_controller         test_connectioncontroller.cpp)
    ouaexp_add_test(ouaexp_tests_connection_data    test_connectiondata.cpp)
    ouaexp_add_test(ouaexp_tests_qtopcua_internals  test_qtopcuainternals.cpp)
    ouaexp_add_test(ouaexp_tests_utils              test_utils.cpp)
    ouaexp_register_test(ouaexp_tests_modules       test_modules.cpp)
    target_link_libraries(ouaexp_tests_modules PRIVATE ouaexp_modules)
endfunction()
