function(ouaexp_configure_common_ui_tests)
    ouaexp_add_ui_test(ouaexp_tests_application         test_application.cpp)
    ouaexp_add_ui_test(ouaexp_tests_connection_dialog   test_connectiondialog.cpp)
    ouaexp_add_ui_test(ouaexp_tests_about_dialog        test_dialogabout.cpp)
    ouaexp_add_ui_test(ouaexp_tests_certificate_details_widget
                       test_certificatedetailswidget.cpp)
    ouaexp_add_ui_test(ouaexp_tests_certificate_summary test_certificatesummarywidget.cpp)
    ouaexp_add_ui_test(ouaexp_tests_certificate_details test_certificatedetailsdialog.cpp)
    ouaexp_add_ui_test(ouaexp_tests_address_space_widget test_addressspacewidget.cpp)
    ouaexp_add_ui_test(ouaexp_tests_datetime_edit test_datetimeedit.cpp)
    ouaexp_add_ui_test(ouaexp_tests_data_access_widget test_dataaccesswidget.cpp)
    ouaexp_add_ui_test(ouaexp_tests_data_view test_dataview.cpp)
    ouaexp_add_ui_test(ouaexp_tests_events_widget test_eventswidget.cpp)
    ouaexp_add_ui_test(ouaexp_tests_history_widget test_historywidget.cpp)
    ouaexp_add_ui_test(ouaexp_tests_attributes_widget test_attributeswidget.cpp)
    ouaexp_add_ui_test(ouaexp_tests_log_widget test_logwidget.cpp)
    ouaexp_add_ui_test(ouaexp_tests_features test_features.cpp)
    ouaexp_add_ui_test(ouaexp_tests_write_value_dialog test_writevaluedialog.cpp)
    ouaexp_add_ui_test(ouaexp_tests_mainwindow_theme    test_mainwindow_theme.cpp)
    ouaexp_add_ui_test(ouaexp_tests_settings_dialog    test_settingsdialog.cpp)
endfunction()
