function(ouaexp_configure_common_ui_tests)
    ouaexp_add_ui_test(ouaexp_tests_application         test_application.cpp)
    ouaexp_add_ui_test(ouaexp_tests_connection_dialog   test_connectiondialog.cpp)
    ouaexp_add_ui_test(ouaexp_tests_certificate_details_widget
                       test_certificatedetailswidget.cpp)
    ouaexp_add_ui_test(ouaexp_tests_certificate_summary test_certificatesummarywidget.cpp)
    ouaexp_add_ui_test(ouaexp_tests_certificate_details test_certificatedetailsdialog.cpp)
    ouaexp_add_ui_test(ouaexp_tests_address_space_widget test_addressspacewidget.cpp)
    ouaexp_add_ui_test(ouaexp_tests_mainwindow_theme    test_mainwindow_theme.cpp)
endfunction()
