name: Test build.sh script on macOS

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - build.sh
      - .github/workflows/test-build-macos.yml
      - src/**
      - '!src/**/*.ts'

concurrency:
  group: build-script-macos-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Run build.sh on ${{ matrix.name }}
    runs-on: ${{ matrix.runner }}
    timeout-minutes: 90
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: macOS-26
            runner: macos-26

          - name: macOS-15
            runner: macos-15

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Run build.sh
        env:
          QT_QPA_PLATFORM: offscreen
        run: bash build.sh --install
